INSERT INTO USER(USERNAME,PASSWORD,EMAIL) VALUES('evan','lucky123456','123456@sina.com');
INSERT INTO USER(USERNAME,PASSWORD,EMAIL) VALUES('jonny','ykcul123456','aaabbb@sina.com');
INSERT INTO USER(USERNAME,PASSWORD,EMAIL) VALUES('sandy','culky123456','cccddd@sina.com');